name: Zephyr

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - transmitter
          - receiver

    steps:
      - name: Checkout application
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: app

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'

      - name: Set up Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@66a907961072acaa85313d2e064e9f071141265a # v1.0.15
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build ${{ matrix.app }}
        run: |
          west build -p always -b native_sim/native/64 \
            -s app/apps/${{ matrix.app }} \
            -d build/${{ matrix.app }}
